module.exports = [
  {
    speakerName: 'Elza Maria Albuquerque',
    speakerTime: '10:00 às 10:30',
    speakerImage: './images/speakers/elza.png',
    speakerImageAlt: 'Foto da Elza Maria Albuquerque. Ela é uma mulher parda, tem cabelos castanhos encaracolados longos. Eles estão soltos. Elza sorri.',
    presentationTitle: 'Como construir uma comunicação para todas as pessoas?',
    presentationSummary: 'Você vai conhecer diversas boas práticas para construirmos uma comunicação mais diversa, inclusiva e acessível para todas as pessoas. A acessibilidade digital é um dos destaques para que isso aconteça. O convite é colaborarmos para um mundo melhor por meio dessa comunicação, um dia de cada vez. Vamos lá?',
    jobTitle: 'Fundadora e CEO da Maria Inclusiva',
    company: 'Maria Inclusiva',
    presentationLink: '',
    linkedin: 'https://www.linkedin.com/in/elza-maria-albuquerque/ ' 
  },
  {
    speakerName: 'Reinaldo Ferraz',
    speakerTime: '10:30 às 11:00',
    speakerImage: './images/speakers/reinaldo-ferraz.png',
    speakerImageAlt: 'Foto do Reinaldo Ferraz. Ele está em um evento, fala ao microfone e segura um prêmio com uma das mãos. Reinaldo tem cabelos curtos lisos, usa um casaco na cor verde.',
    presentationTitle: 'Pessoas idosas na web',
    presentationSummary: "A população está envelhecendo. O que acontece, muitas vezes, é que cada vez mais pessoas enfrentam desafios relacionados à idade. Por isso, precisamos considerar a acessibilidade no dia a dia. Neste encontro, conheça as boas práticas que beneficiam esse grupo de pessoas usuárias que está aumentando cada vez mais e que, possivelmente, faremos parte dele.",
    jobTitle: 'Project Manager',
    company: 'NIC.br',
    presentationLink: '',
    linkedin: 'https://www.linkedin.com/in/reinaldoferraz/'
  },
  {
    speakerName: 'Alex Barboza',
    speakerTime: '11:00 às 11:30',
    speakerImage: './images/speakers/alex-barboza.png',
    speakerImageAlt: 'Foto do Alex Barboza em uma área com imagens coloridas ao fundo. Ele é branco, tem cabelos castanhos curtos, usa uma blusa preta. Alex sorri e posa para a foto.',
    presentationTitle: 'Acessibilidade para Android - desafios e ferramentas',
    presentationSummary: 'Durante a palestra, você vai conhecer as barreiras enfrentadas por pessoas usuárias com deficiências visuais ao lidar com aplicações móveis. Além disso, você vai saber as causas desses problemas e quais são as ferramentas disponíveis para pessoas desenvolvedoras Android com o objetivo de minimizar os problemas de acessibilidade.',
    miniBio: 'Sou técnico em Informática pelo Centro Paula Souza, Bacharel em Sistemas de Informação pela USP e atualmente mestrando em Engenharia de Software também pela USP. Meu tema de pesquisa é acessibilidade para aplicações móveis, com foco em técnicas e ferramentas para identificação automática de violações de acessibilidade. Na indústria, atuo como desenvolvedor mobile há 7 anos. No Brasil, fui desenvolvedor Android no Itaú. Em Portugal, trabalhei como desenvolvedor Android para a Aubay nas áreas financeira e de telecomunicações. Atualmente trabalho também como dev Android para a Swiss Post (os correios da Suíça)',
    jobTitle: 'Desenvolvedor Android',
    company: 'Swiss Post',
    presentationLink: '',
    linkedin: 'https://www.linkedin.com/in/alex-r-a3319214b'
  },
  {
    speakerName: 'Vitor David',
    speakerTime: '11:30 às 12:00',
    speakerImage: './images/speakers/vitor-david.png',
    speakerImageAlt: 'Foto do Vitor David em um lugar fechado. Ele tem cabelos curtos, usa barba e blusa preta. Vitor sorri e está com as duas mãos unidas abaixo do queixo.',
    presentationTitle: 'Processo e métricas de acessibilidade',
    presentationSummary: 'Nesta palestra, você vai aprender mais sobre o processo de acessibilidade em times de produtos e como metrificar a acessibilidade.',
    miniBio: 'Designer formado a uns 8 anos, com MBA em Mídias Sociais e cursando MBA em Ux pela Puc. Atuei em projetos de acessibilidade envolvendo Grupo pão de açúcar, Hand Talk, Bradesco Seguros e outros.',
    jobTitle: 'Accessibility Product Designer',
    company: 'Bradesco Seguros',
    presentationLink: '',
    linkedin: 'https://www.linkedin.com/in/vitordavid/',
  },
  {
    speakerName: 'Bruno Pulis',
    speakerTime: '14:00 às 14:30',
    speakerImage: './images/speakers/bruno-pulis.png',
    speakerImageAlt: 'Foto do Bruno Pulis. Ele tem cabelos castanhos cortados bem curtos, tem barba, usa óculos e uma blusa branca. O fundo da foto é azul.',
    presentationTitle: 'Uma visão sobre testes de acessibilidade',
    presentationSummary: 'Nessa palestra, Bruno vai demonstrar algumas abordagens de testes automatizados para acessibilidade. Além disso, ele vai contar como podemos integrar acessibilidade dentro da pirâmide de testes.',
    miniBio: 'Desenvolvedor de software especialista em acessibilidade web, formado pela Faculdade Pitágoras, com 15 anos de experiência. Apaixonado por acessibilidade, criou o Awesome A11y. Curioso. Viciado em Star Wars e café.',
    jobTitle: 'Analista de Acessibilidade',
    company: 'NTT Data',
    presentationLink: '',
    linkedin: 'https://www.linkedin.com/in/pulis/',
    github: 'https://github.com/brunopulis',
    instagram: 'https://instagram.com/brunopulis',
    twitter: 'https://twitter.com/obrunopulis', 
  },
  {
    speakerName: 'Mariana Pulis',
    speakerTime: '14:30 às 15:00',
    speakerImage: './images/speakers/mariana-pulis.png',
    speakerImageAlt: 'Foto da Mariana Pulis. Ela é branca, tem cabelos castanhos lisos e longos, estão de lado. Ela usa batom e uma blusa estampada sem mangas.',
    presentationTitle: 'Comunicação acessível e Libras',
    presentationSummary: 'Nesta palestra, vamos conversar sobre surdez, Libras e formas de comunicação para que todas as pessoas tenham equidade de aprendizagem, informação e lazer.',
    miniBio: 'Sou Mariana Pulis, tenho 31 anos, natural de Petrópolis-RJ, residente em BH. Trabalho como analista de testes de acessibilidade digital e sou intérprete de Libras.',
    presentationLink: '',
    jobTitle: 'Analista de Acessibilidade',
    company: 'NTT Data',
    linkedin: 'https://www.linkedin.com/in/marilibras/'
  },
  {
    speakerId: 'two',
    speakerName: 'Eduardo Lino e Cadu Ribeiro',
    speakerTime: '15:00 - 15:30',
    speakerImage: './images/speakers/edu-cadu.png',
    speakerImageAlt: 'Montagem com duas fotos: uma foto é do Eduardo Zangrossi e outra do Cadu Ribeiro. A foto do Eduardo é colorida e do Cadu está em preto e branco. Eduardo tem cabelos castanhos curtos, usa óculos e blusa preta. Cadu tem cabelos curtos e barba.',
    presentationTitle: '70% pessoas, 30% técnico: O lado humano do design acessível',
    presentationSummary: 'Junte-se a nós para uma conversa descontraída com Eduardo e Cadu! Eles vão compartilhar suas vivências sobre a importância do toque humano na criação de projetos acessíveis. Descubra como essa perspectiva mudou vidas e como a acessibilidade se tornou parte do dia a dia dos palestrantes. Durante o encontro, vamos explorar, juntos, como integrar a acessibilidade em nossos próprios projetos e na sociedade.',
    miniBio: 'Eduardo Zangrossi Lino: Product Designer com mais de 11 anos de experiência na indústria tech e com foco em Acessibilidade Web e Digital e experiência em Desenvolvimento Front-end, integra equipes multidisciplinares de design e desenvolvimento durante todo o ciclo de criação e growth de produtos digitais, atuando como facilitador para uma comunicação mais eficaz entre as equipes e introduzindo soluções inovadoras e inclusivas. Cadu Ribeiro: Designer, professor e pesquisador. Mestre em Design pela PUC-Rio e especialista em Ergodesign, usabilidade e interação humano-computador pela mesma instituição. Já contribuiu para diversas startups no Rio de Janeiro, São Paulo e Portugal montando times de UX e liderando equipes, sempre com foco em projetos inclusivos.',
    jobTitle1: 'Product Designer',
    jobTitle2: 'Designer, Professor e pesquisador',
    presentationLink: '',
    linkedin1: 'https://www.linkedin.com/in/eduzangrossi/',
    linkedin2: 'https://www.linkedin.com/in/caduxribeiro/'
  },
  {
    speakerName: 'Doriane Vasconcelos',
    speakerTime: '15:30 - 16:30',
    speakerImage: './images/speakers/doriane-vasconcelos.png',
    speakerImageAlt: '',
    presentationTitle: 'A importância da audiodescrição nos espaços corporativos',
    presentationSummary: 'Durante o encontro, vamos falar sobre a audiodescrição e como ela colabora para promover inclusão no trabalho. É um recurso que estimula a atuação, a participação, a interação e o protagonismo das pessoas com deficiência visual e de outros públicos que o acessam.',
    miniBio: 'Bacharela em Administração com Especialização em Gestão de Pessoas pelo IFBA, Bacharelanda Interdisciplinar em Humanidades com Especialização em Estudos Jurídicos na UFBA, empregada pública na Embasa, Consultora Técnica e Cognitiva em Audiodescrição,Acessibilidade e Inclusão e, defendo a diversidade humana nas organizações. Sou colaboradora em projetos da UFRJ, Fiocruz, IFBA, IFRJ e Movimento WEB Para Todos. Por 18 meses participei de projeto na UNESP - Bauru. Sou Fundadora e Coordenadora do coletivo: Consultores em Audiodescrição Brasil e da @equipead_dorianevasconcelos. Além disso, membra do Comitê de Diversidade, Equidade e Inclusão na Embasa. Atuo como Formadora, Pesquisadora, Escritora, Palestrante, Criadora de Conteúdo digital.',
    presentationLink: '',
    jobTitle: 'Audiodescritora',
    company: 'Embasa',
    linkedin: 'https://www.linkedin.com/in/doriane-vasconcelos-de-oliveira-156301191/'
  }
]